# Configuração inicial
SAFE_ZONE_RADIUS = 4
DEBUFF_PERCENTAGE = 0.2
DEBUFF_TURNS = 10
STUN_TURNS = 5
NUM_MINION_ARQUEIRO, NUM_MINION_GUERREIRO, NUM_MINION_MAGO = 3, 3, 3
NUM_TRAP_DEBUFF, NUM_TRAP_STUN = 2, 2