# Configuração inicial
SAFE_ZONE_RADIUS = 2
FOV_PLAYER = 6
DEBUFF_PERCENTAGE = 0.2
DEBUFF_TURNS = 10
STUN_TURNS = 5
NUM_MINION_ARQUEIRO, NUM_MINION_GUERREIRO = 10, 10
NUM_TRAP_DEBUFF, NUM_TRAP_STUN = 20, 20